version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: ./streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
