# version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      # - ./backend/sqlite_data:/sql_app.db  
      - ./backend:/backend 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/frontend            
      - /frontend/node_modules 

networks:
  app-network:
    driver: bridge

# volumes:
#   sqlite_data: